language: php

env:
  global:
    - 'FTP_USER=akanggebot12'
    - 'FTP_PASS=1205akang'

script:
  - "curl -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com -Q 'mkd public_html/praktek-4c'"
  - "curl -T halo.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/praktek-4c/"